# Generated by Django 3.2 on 2022-07-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='project_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
