# Generated by Django 4.1 on 2022-08-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220729_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='project_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
