# Generated by Django 4.1 on 2022-08-14 22:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://bit.ly/3PiQSmV', max_length=255, verbose_name='image'),
        ),
    ]
