# Generated by Django 4.1 on 2022-08-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animation',
            old_name='is_favourite',
            new_name='favourites',
        ),
    ]
